In [ ]:
#Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [1]:
import numpy as np


In [2]:
#. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
original_arr=np.random.randint(1,100,(3,3))
transpose_arr=original_arr.T
print(f'Original Array {original_arr}')
print(f'Transpose Array {transpose_arr}')

Original Array [[51 13 53]
 [71 19  6]
 [58 44 19]]
Transpose Array [[51 71 58]
 [13 19 44]
 [53  6 19]]


In [3]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
arr=np.arange(0,20,2)
reshape_arr=arr.reshape(2,5)
print(reshape_arr)
reshape_arr2=reshape_arr.reshape(5,2)
print()
print(reshape_arr2)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [4]:
#Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
arr=np.random.rand(16).reshape(4,4)


In [5]:
ver_b=np.zeros(4)
hor_b=np.zeros(6).reshape(6,1)



In [6]:
arr1=np.vstack((ver_b,arr,ver_b))
arr1
arr2=np.hstack((hor_b,arr1,hor_b))
arr2


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.9461771 , 0.64028929, 0.74598848, 0.74540648,
        0.        ],
       [0.        , 0.46119593, 0.93836567, 0.49096739, 0.67906015,
        0.        ],
       [0.        , 0.38592029, 0.66342589, 0.41051004, 0.0853869 ,
        0.        ],
       [0.        , 0.98158294, 0.68023845, 0.54068714, 0.50242511,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [7]:
# Using NumPy, create an array of integers from 10 to 60 with a step of 5.
arr=np.arange(10,60,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55]


In [8]:
# Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
word=['python', 'numpy', 'pandas']
word_arr=np.array(word)
Upper_arr=np.char.upper(word_arr)
lower_arr=np.char.lower(word_arr)
title_arr=np.char.title(word_arr)
print(Upper_arr)
print(lower_arr)
print(title_arr)


['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [46]:
# Generate a NumPy array of words. Insert a space between each character of every word in the array.
sen='India is my country'
a=np.array(sen)



AttributeError: 'numpy.ndarray' object has no attribute 'lower'

In [10]:
#Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


In [11]:
# Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
a=np.eye(5)
for i in range(a.shape[0]):
    print(a[i][i])

1.0
1.0
1.0
1.0
1.0


In [13]:
# Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array
np.random.randint(0,1000,(1,100))
l=[]
for i in range(2,101):
    k=0
    for j in range(2,i):
        if i%j==0:
            k+=1
    if k==0:
        l.append(i)
print(l)
        
            
            
        
        
     

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [41]:
# Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
temp=np.random.randint(1,100,30)
print(temp)
for i in range(0,30,7):
    t_sum=0
    if i==28:
        break
    for j in range(i,i+7):
        t_sum=t_sum+temp[j]
    print(f'Average tempearture for week {(i/7)+1} is {t_sum/7}')

[45 61 61  6 33 27 55 63 95 91 93 33 40 81 84  8 11 22 47 91 41 83 32 43
 28 14 43 48 11 20]
Average tempearture for week 1.0 is 41.142857142857146
Average tempearture for week 2.0 is 70.85714285714286
Average tempearture for week 3.0 is 43.42857142857143
Average tempearture for week 4.0 is 41.57142857142857


1